---
title: "Chimpanzees"
author: "Stat 341 — Spring 2017"
date: "April, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
require(rethinking)
require(mosaic)
require(ggformula)
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  eval = FALSE)
```

## Chimpanzees

```{r, chunk10.1, eval = TRUE}
library(rethinking)
data(chimpanzees)
Chimps <- chimpanzees %>% 
  select(- recipient) %>%   # to avoid missing data when making Stan models
  mutate( 
    combo = paste0(prosoc_left, "/", condition))  # useful for plotting 
head(Chimps)
```

### Five models

#### m10.1

```{r, results = 'hide', message = FALSE, error = FALSE}
m10.1 <- 
  map(
    alist(pulled_left ~ dbinom(1, p),
          logit(p) <- a,
          a ~ dnorm(0, 10)),
    data = Chimps)
```


#### m10.2

```{r, results = 'hide', message = FALSE, error = FALSE}
m10.2 <- 
  map(
    alist(
      pulled_left ~ dbinom(1, p),
      logit(p) <- a + bp * prosoc_left,
      a ~ dnorm(0, 10),
      bp ~ dnorm(0, 10)
    ),
    data = Chimps)
```

#### m10.3

```{r, results = 'hide', message = FALSE, error = FALSE}
m10.3 <- 
  map(
    alist(
      pulled_left ~ dbinom(1, p),
      logit(p) <- a + (bp + bpC * condition) * prosoc_left,
      a ~ dnorm(0, 10),
      bp ~ dnorm(0, 10),
      bpC ~ dnorm(0, 10)
    ),
    data = Chimps)
```

```{r, chunk10.12, include = FALSE}
# re-use map fit to get the formula
m10.3stan <- 
  map2stan(
    m10.3, data = Chimps,
    iter = 1e4, warmup = 1000, refresh = 0)
```

#### m10.4

```{r, chunk10.14}
m10.4 <- map2stan(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a[actor] + (bp + bpC * condition) * prosoc_left,
    a[actor] ~ dnorm(0, 10),
    bp ~ dnorm(0, 10),
    bpC ~ dnorm(0, 10)
  ),
  data = Chimps,
  chains = 2, iter = 2500, warmup = 500, refresh = 0
)
```

#### m12.4

```{r, chunk12.21}
m12.4 <- map2stan(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <-
      a + a_actor[actor] + (bp + bpC * condition) * prosoc_left,
    a_actor[actor] ~ dnorm(0, sigma_actor),
    a ~ dnorm(0, 10),
    bp ~ dnorm(0, 10),
    bpC ~ dnorm(0, 10),
    sigma_actor ~ dcauchy(0, 1)
  ),
  data = Chimps,
  warmup = 1000, iter = 5000,
  chains = 4, cores = 3, refresh = 0
)
```

